version: "3"

services:
  pg:
    container_name: postgres-lab
    image: postgres:11.22-bullseye
    network_mode: host
    volumes:
      - name-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_DB=app
      - PGPORT=5431

volumes:
  name-data:
